### ISSUE TITLE
MIT OCW courses not available anywhere on YouTube

### ISSUE THREAD

**Issue by th3sn3k** [llSourcell/Learn_Machine_Learning_in_3_Months#13]
This Issue started a day back It seems all videos from MIT OCW have been blocked on every country I checked with YouTube restriction checker.

Hope you can suggest an alternative to the OCW courses.

**Comment by AnupamKhurana** [comment]
Yes, I am facing the same issue. "MIT OpenCourseWare" on youtube isn't available for now in India at least.

**Comment by lamhoangtung** [comment]
Have you tried the OpenCourseWare website instead ? It’s working fine for
me (i’m in vietnam btw)
Vào Th 2, 18 thg 6, 2018 lúc 12:59 AnupamKhurana <notifications@github.com>
đã viết:

**Comment by AnupamKhurana** [comment]
Same problem on the OpenCourseWare website...

**Comment by yaakash** [comment]
Website of OCW uses a different player, in case of Linear algebra course, its running.

**Comment by cksajil** [comment]
I think the problem is fixed now. All videos are available in YouTube as before.

**Comment by AnupamKhurana** [comment]
issue is resolved

**Comment by happytalkman** [comment]
goooood
