### ISSUE TITLE
Is it expected to read/watch all the resources listed under a week?

### ISSUE THREAD

**Issue by olavfosse** [llSourcell/Learn_Machine_Learning_in_3_Months#25]
https://www.youtube.com/watch?v=4LKJ1zyH6aI

**Comment by momochand** [comment]
You've answered yourself. 'Best' case you finish things in three months. Personally I disagree with that, you need time to think about things to truly absorb it. For the many new guys following this course I'd recommend expecting 3 to 6 months to finish it. You could risk burning out otherwise.

**Comment by kartikeyshaurya** [comment]
if you are up to time don't have time and handle the heat just go for it
