### ISSUE TITLE
About the sequence of subjects

### ISSUE THREAD

**Issue by denisb411** [llSourcell/Learn_Machine_Learning_in_3_Months#9]
I see that Linear Algebra cames before learning Calculus. Is this right?

My opinion is that:
1 - Differential and Integral Calculus
2 - Linear Algebra
3 - Multivariable Calculus
4 - Probability
5 - Algorithms

**Comment by yaakash** [comment]
Well, Linear algebra is required to come before calculus, its also mentioned in lecture of "big picture of calculus" by gilbert strang.

**Comment by Sajjadmanal** [comment]
Yes. I believe that too.
